# Generated by Django 5.1.15 on 2026-06-13 20:00
"""Initial migration for the custom User model."""  # noqa: D100

import uuid

from django.db import migrations, models

import accounts.manager


class Migration(migrations.Migration):  # noqa: D101
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            managers=[
                ("objects", accounts.manager.UserManager()),
            ],
        ),
    ]
