# Generated by Django 5.1.15 on 2026-06-13 21:53
"""Initial migration for the Feature model, the pg_trgm extension, and the trigram GIN index."""  # noqa: D100

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("geometry", django.contrib.gis.db.models.fields.GeometryField(spatial_index=False, srid=4326)),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geometry"], name="features_fe_geometr_fe76e8_gist"
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["updated_at", "id"], name="features_fe_updated_9b15e2_btree"
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["created_at", "id"], name="features_fe_created_c3a9af_btree"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=(
                'CREATE INDEX "features_props_name_trgm_idx" '
                'ON "features_feature" '
                "USING gin ((properties ->> 'name') gin_trgm_ops);"
            ),
            reverse_sql='DROP INDEX IF EXISTS "features_props_name_trgm_idx";',
        ),
    ]
