# Generated by Django 5.1.15 on 2026-06-13 23:01
"""Allow `created_by` to be NULL so the seed command can attribute features to no user."""  # noqa: D100

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("features", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
